# Generated by Django 3.0.8 on 2020-08-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200730_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notesfile',
            field=models.FileField(null=True, upload_to='posts/'),
        ),
    ]
