# Generated by Django 3.0.8 on 2020-08-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_notesfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='notesfile',
        ),
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
