# Generated by Django 3.0.3 on 2020-07-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200725_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
