# Generated by Django 3.0.3 on 2020-07-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200726_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, default='images/default_profile.png', upload_to='images/'),
        ),
    ]
